//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public int ObjectID { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public bool IsThumbnail { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int Content_OID { get; set; }
    
        public virtual Content Content { get; set; }
    }
}
